import { useState } from 'react'
import { Sparkles } from 'lucide-react'
import { requestAiTips } from '../lib/ai'

interface AiTipsProps {
  resumeText: string
  jdText: string
  score: number
  grade: string
  missing: string[]
  listOnly: string[]
  fmtFails: string[]
  miscFails: string[]
}

function renderParagraph(text: string) {
  return text.split('**').map((part, i) => (i % 2 === 1 ? <strong key={i}>{part}</strong> : part))
}

export function AiTips({ resumeText, jdText, score, grade, missing, listOnly, fmtFails, miscFails }: AiTipsProps) {
  const [open, setOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [tips, setTips] = useState<string | null>(null)

  const ask = async () => {
    setSaving(true)
    setError(null)
    setTips(null)
    try {
      const result = await requestAiTips(resumeText, jdText, { score, grade, missing, listOnly, fmtFails, miscFails })
      setTips(result)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to get AI tips.')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="inline-flex items-center gap-1.5 h-7 px-1 rounded-md text-[13px] text-muted hover:text-body transition-colors cursor-pointer"
      >
        <Sparkles className="size-3.5" aria-hidden="true" />
        {open ? 'Hide AI tips' : 'Get AI improvement tips'}
      </button>
      {open && (
        <div className="mt-2 bg-panel2/60 border border-edge rounded-md p-3 space-y-3 max-w-2xl">
          <p className="text-[11px] text-muted leading-relaxed">
            Tips are generated by your Ollama server (qwen3.5) — the resume and job text are sent to your AI endpoint, and
            nothing is stored.
          </p>
          <div className="flex items-center gap-4">
            <button
              type="button"
              onClick={ask}
              disabled={saving}
              className="inline-flex items-center h-8 px-3 rounded-md bg-accent text-white text-[13px] font-medium transition-colors hover:opacity-90 disabled:opacity-50 cursor-pointer"
            >
              {saving ? 'Asking…' : tips ? 'Ask again' : 'Generate improvement tips'}
            </button>
          </div>
          {error && <p className="text-[12px] text-bad">{error}</p>}
          {tips && typeof tips === 'string' && (
            <div className="border-t border-edge pt-3 space-y-2.5">
              {tips
                .split(/\n{2,}/)
                .map((p) => p.replace(/\n/g, ' ').trim())
                .filter(Boolean)
                .map((p, i) => (
                  <p key={i} className="text-[13px] leading-relaxed text-body/90">
                    {renderParagraph(p)}
                  </p>
                ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}
