import type { AtsPreset, PresetId } from '../types'

export const ATS_PRESETS: Record<PresetId, AtsPreset> = {
  auto: {
    id: 'auto',
    name: 'Auto / General',
    weights: { keyword: 45, format: 25, bullet: 20, contact: 10 },
    minOccurrences: 1,
    tablePenalty: 20,
    twoColPenalty: 12,
    standardsMissingPenalty: 6,
    tips: [
      'Keep a single-column layout with standard section headers (Summary, Experience, Education, Skills).',
      'Mirror the exact wording of the job posting — ATS keyword matching is literal, not synonymous.',
      'Upload a clean PDF or DOCX; never submit tables, images, or text boxes.',
      'Use the ATS preset menu if you know which system the company runs.',
    ],
  },
  workday: {
    id: 'workday',
    name: 'Workday',
    weights: { keyword: 45, format: 30, bullet: 15, contact: 10 },
    minOccurrences: 1,
    tablePenalty: 35,
    twoColPenalty: 25,
    standardsMissingPenalty: 8,
    tips: [
      'Workday powers ~38% of large employers (Apple, Walmart, Disney, McKinsey, most banks).',
      'Single-column layout with standard section headers parses best; two-column drops to ~64% parse accuracy.',
      'The Skills section is read closely — list the exact terms from the job description there.',
      'PDF and DOCX both work; avoid tables, images, and decorative fonts.',
      'Workday long forms often re-ask resume fields — keep them consistent with what you upload.',
    ],
  },
  greenhouse: {
    id: 'greenhouse',
    name: 'Greenhouse',
    weights: { keyword: 40, format: 25, bullet: 25, contact: 10 },
    minOccurrences: 1,
    tablePenalty: 15,
    twoColPenalty: 8,
    standardsMissingPenalty: 6,
    tips: [
      'Greenhouse is the default for tech scale-ups (Netflix, Stripe, Airbnb, Shopify, Databricks).',
      'PDF is strongly preferred; Greenhouse reads headers and footers, unlike Lever.',
      'Two-column layouts are survivable here (~71% parse), but single column is still safer.',
      'Greenhouse is used with structured interview scorecards — metric-rich bullets help human reviewers.',
      'Exact JD keywords matter less than in Taleo; relevance and phrasing carry weight.',
    ],
  },
  taleo: {
    id: 'taleo',
    name: 'Taleo / Oracle',
    weights: { keyword: 50, format: 30, bullet: 10, contact: 10 },
    minOccurrences: 2,
    tablePenalty: 45,
    twoColPenalty: 35,
    standardsMissingPenalty: 10,
    tips: [
      'Taleo/Oracle still powers much of legacy finance and enterprise (JPMorgan, Goldman Sachs, hospitals).',
      'The harshest parser: two-column drops to ~47% parse accuracy. Single column, always.',
      'Keyword matching is exact string matching — use the JD exact phrasing, not synonyms.',
      'Older Taleo instances reward repetition: mention a key term 2-3 times, not once.',
      'DOCX is preferred over PDF; avoid headers/footers, text boxes, and tables entirely.',
      'Non-standard section headers (e.g. "Professional Journey") can break parsing — use "Experience".',
    ],
  },
  lever: {
    id: 'lever',
    name: 'Lever',
    weights: { keyword: 40, format: 25, bullet: 25, contact: 10 },
    minOccurrences: 1,
    tablePenalty: 15,
    twoColPenalty: 8,
    standardsMissingPenalty: 6,
    tips: [
      'Lever is common at AI-native and dev-tooling companies (xAI, Perplexity, Cursor, Vercel, Ramp).',
      'Lever ignores headers and footers — don\'t stash keywords there.',
      'PDF parses best; two-column is workable (~68%) but not ideal.',
      'Recruiters search Lever\'s database by skill terms — keep skills section complete and exact.',
      'Lever jobs pages are simple; make sure your LinkedIn title matches your resume headline.',
    ],
  },
  icims: {
    id: 'icims',
    name: 'iCIMS',
    weights: { keyword: 42, format: 28, bullet: 18, contact: 12 },
    minOccurrences: 1,
    tablePenalty: 30,
    twoColPenalty: 20,
    standardsMissingPenalty: 8,
    tips: [
      'iCIMS serves mid-market and healthcare (Uber, Best Buy, Toyota NA, many hospital networks).',
      'Two-column layouts are heavily penalized (~47% parse) — single column only.',
      'iCIMS reads headers partially; keep contact info in the body, not headers/footers.',
      'Many iCIMS flows add assessments after application — don\'t get screened by the resume only.',
      'DOCX parses slightly better than PDF here if you have the choice.',
    ],
  },
  ashby: {
    id: 'ashby',
    name: 'Ashby',
    weights: { keyword: 40, format: 25, bullet: 25, contact: 10 },
    minOccurrences: 1,
    tablePenalty: 15,
    twoColPenalty: 10,
    standardsMissingPenalty: 6,
    tips: [
      'Ashby is rapidly growing at fast startups (Notion, Linear, Ramp, Mercury, most recent YC).',
      'PDF parses best; single column preferred, two-column tolerable (~70%).',
      'Ashby pulls public LinkedIn data during application — your LinkedIn headline must match your resume.',
      'Clean, structured bullets with metrics are what human reviewers at startups look for.',
    ],
  },
}

export const PRESET_IDS = Object.keys(ATS_PRESETS) as PresetId[]